#!/usr/bin/env python3
"""Generate the DCAT catalog TTL and SVG lineage graph for the Exploitation Zone.

The Turtle file is loaded into GraphDB. The SVG is a report-friendly rendering of
the same catalog relationships. The script uses only the Python standard library.
"""

from __future__ import annotations

import argparse
from html import escape as esc
from pathlib import Path


VW, VH = 1080, 700
NW, NH, NR = 152, 46, 7

KINDS = {
    "source": {"fill": "#E6F1FB", "stroke": "#378ADD", "text": "#0C447C"},
    "data_product": {"fill": "#EAF3DE", "stroke": "#639922", "text": "#27500A"},
    "supporting_asset": {"fill": "#FAEEDA", "stroke": "#BA7517", "text": "#633806"},
    "consumer": {"fill": "#EEEDFE", "stroke": "#7F77DD", "text": "#3C3489"},
}

NODES = [
    {
        "id": "trusted_lastfm_tracks",
        "label": "Trusted Last.fm Tracks",
        "kind": "source",
        "desc": "Cleaned Last.fm track metadata.",
        "path": "s3://trusted/structured/lastfm/delta/tracks_clean_delta",
    },
    {
        "id": "trusted_musicbrainz_isrc",
        "label": "Trusted MusicBrainz ISRC",
        "kind": "source",
        "desc": "Cleaned MusicBrainz ISRC resolution records.",
        "path": "s3://trusted/structured/musicbrainz/delta/isrc_clean_delta",
    },
    {
        "id": "trusted_reccobeats_audio",
        "label": "Trusted ReccoBeats Audio",
        "kind": "source",
        "desc": "Cleaned ReccoBeats audio descriptors.",
        "path": "s3://trusted/structured/reccobeats/delta/audio_features_clean_delta",
    },
    {
        "id": "trusted_trends",
        "label": "Trusted Trends",
        "kind": "source",
        "desc": "Cleaned social trend events.",
        "path": "s3://trusted/semi_structured/trends/delta/trends_clean_delta",
    },
    {
        "id": "trusted_feedback",
        "label": "Trusted Feedback",
        "kind": "source",
        "desc": "Validated recommendation feedback events.",
        "path": "s3://trusted/recommender/feedback/delta/recommendation_feedback_clean_delta",
    },
    {
        "id": "curated_song_catalog",
        "label": "Curated Song Catalog",
        "kind": "data_product",
        "domain": "Music Catalog",
        "owner": "Music Catalog domain",
        "desc": "Song-level catalog combining identity, external IDs, and audio descriptors.",
        "path": "s3://exploitation/structured/song_audio_features/delta/song_audio_features_delta",
        "quality": [
            "Valid ISRC when present",
            "Stable song identity",
            "Audio features cast to numeric ranges",
        ],
    },
    {
        "id": "song_trend_intelligence",
        "label": "Song Trend Intelligence",
        "kind": "data_product",
        "domain": "Social Trend Intelligence",
        "owner": "Social Trend Intelligence domain",
        "desc": "Song-level social trend metrics.",
        "path": "s3://exploitation/semi_structured/trends/delta/song_trend_aggregates_delta",
        "quality": [
            "Valid source trend records",
            "Non-negative engagement counters",
            "Documented trend score logic",
        ],
    },
    {
        "id": "song_recommender_features",
        "label": "Song Recommender Features",
        "kind": "supporting_asset",
        "desc": "Internal feature table joining catalog and trend signals.",
        "path": "s3://exploitation/recommender/song_features/delta/song_recommender_features_delta",
    },
    {
        "id": "song_embedding_snapshots",
        "label": "Song Embedding Snapshots",
        "kind": "supporting_asset",
        "desc": "CLIP text embedding snapshots for song candidates.",
        "path": "s3://exploitation/recommender/song_embeddings/delta/song_embedding_snapshots_delta",
    },
    {
        "id": "song_recommender_embeddings",
        "label": "Milvus Song Embeddings",
        "kind": "supporting_asset",
        "desc": "Latest song vectors served by Milvus for nearest-neighbor search.",
        "path": "milvus://song_recommender_embeddings",
    },
    {
        "id": "real_time_recommender",
        "label": "Real-time Recommender",
        "kind": "consumer",
        "desc": "Streaming service matching image embeddings to song embeddings.",
        "path": "",
    },
    {
        "id": "recommendation_events",
        "label": "Recommendation Event Logs",
        "kind": "supporting_asset",
        "desc": "Recommendation event logs generated by the real-time recommender.",
        "path": "s3://consumption/recommendations/recommendation_events/",
    },
    {
        "id": "feedback_events",
        "label": "Feedback Events",
        "kind": "supporting_asset",
        "desc": "Validated feedback events enriched with recommendation outcome flags.",
        "path": "s3://consumption/recommendations/feedback_events_delta",
    },
    {
        "id": "feedback_summary",
        "label": "Feedback Summary",
        "kind": "supporting_asset",
        "desc": "Dashboard KPI table aggregating acceptance, skip, and satisfaction metrics.",
        "path": "s3://consumption/recommendations/feedback_summary_delta",
    },
    {
        "id": "recommendation_outcomes",
        "label": "Recommendation Outcomes",
        "kind": "data_product",
        "domain": "Recommendation Intelligence",
        "owner": "Recommendation Intelligence domain",
        "desc": "Connects each recommendation request with the selected song and user feedback.",
        "path": "s3://consumption/recommendations/recommendation_outcomes_delta",
        "quality": [
            "Intended grain is one row per request_id",
            "Feedback action must be accepted, selected_candidate, skipped, or external_selection",
            "Satisfaction score must be between 1 and 5 when present",
            "Invalid feedback records are stored in rejected outputs",
        ],
    },
    {
        "id": "streamlit_dashboard",
        "label": "Streamlit Dashboard",
        "kind": "consumer",
        "desc": "Consumption layer for trend, catalog, recommendation, and data-status monitoring.",
        "path": "",
    },
]

POSITIONS = {
    "trusted_lastfm_tracks": (28, 60),
    "trusted_musicbrainz_isrc": (28, 140),
    "trusted_reccobeats_audio": (28, 220),
    "trusted_trends": (28, 340),
    "trusted_feedback": (28, 480),
    "curated_song_catalog": (250, 150),
    "song_trend_intelligence": (250, 335),
    "song_recommender_features": (470, 245),
    "song_embedding_snapshots": (470, 350),
    "song_recommender_embeddings": (470, 455),
    "real_time_recommender": (690, 360),
    "recommendation_events": (700, 500),
    "feedback_events": (250, 500),
    "feedback_summary": (470, 595),
    "recommendation_outcomes": (700, 600),
    "streamlit_dashboard": (900, 405),
}

EDGES = [
    ("trusted_lastfm_tracks", "curated_song_catalog", "derived from"),
    ("trusted_musicbrainz_isrc", "curated_song_catalog", "derived from"),
    ("trusted_reccobeats_audio", "curated_song_catalog", "derived from"),
    ("trusted_trends", "song_trend_intelligence", "derived from"),
    ("curated_song_catalog", "song_recommender_features", "feeds"),
    ("song_trend_intelligence", "song_recommender_features", "feeds"),
    ("song_recommender_features", "song_embedding_snapshots", "embedded as"),
    ("song_embedding_snapshots", "song_recommender_embeddings", "upserted to"),
    ("song_recommender_embeddings", "real_time_recommender", "served to"),
    ("real_time_recommender", "recommendation_events", "writes"),
    ("trusted_feedback", "feedback_events", "enriched as"),
    ("trusted_feedback", "feedback_summary", "aggregated as"),
    ("recommendation_events", "recommendation_outcomes", "joined into"),
    ("trusted_feedback", "recommendation_outcomes", "joined into"),
    ("recommendation_outcomes", "streamlit_dashboard", "consumed by"),
    ("feedback_summary", "streamlit_dashboard", "consumed by"),
    ("feedback_events", "streamlit_dashboard", "consumed by"),
    ("curated_song_catalog", "streamlit_dashboard", "consumed by"),
    ("song_trend_intelligence", "streamlit_dashboard", "consumed by"),
]


def node_uri(node_id: str) -> str:
    return f"bdm:{node_id}"


def turtle_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


def camel_case(value: str) -> str:
    return "".join(part.capitalize() for part in value.split("_"))


def format_for_path(path: str) -> str:
    if path.startswith("s3://") and path.endswith("/"):
        return "Object prefix"
    if path.startswith("s3://"):
        return "Delta Lake"
    if path.startswith("milvus://"):
        return "Milvus collection"
    return "Resource"


def relationship_predicate(label: str) -> str:
    return {
        "feeds": "bdm:feeds",
        "embedded as": "bdm:embeddedAs",
        "upserted to": "bdm:upsertedTo",
        "served to": "bdm:servedTo",
        "writes": "bdm:writes",
        "enriched as": "bdm:enrichedAs",
        "aggregated as": "bdm:aggregatedAs",
        "joined into": "bdm:joinedInto",
        "consumed by": "bdm:consumedBy",
    }[label]


def write_ttl(output_path: Path) -> None:
    data_products = [node_uri(n["id"]) for n in NODES if n["kind"] == "data_product"]
    lines = [
        "@prefix bdm: <https://bdm.example.org/catalog/> .",
        "@prefix dcat: <http://www.w3.org/ns/dcat#> .",
        "@prefix dct: <http://purl.org/dc/terms/> .",
        "@prefix prov: <http://www.w3.org/ns/prov#> .",
        "@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .",
        "",
        "bdm:exploitationCatalog a dcat:Catalog ;",
        '    dct:title "BDM Exploitation Zone Data Product Catalog" ;',
        '    dct:description "DCAT-based metadata catalog for Exploitation Zone data products, supporting assets, lineage sources, and consumers." ;',
        "    dcat:dataset " + ", ".join(data_products) + " .",
        "",
    ]

    incoming_lineage: dict[str, list[str]] = {}
    for source, target, label in EDGES:
        if label in {"derived from", "joined into"}:
            incoming_lineage.setdefault(target, []).append(source)

    for node in NODES:
        node_id = node["id"]
        rdf_type = "dcat:Dataset" if node["kind"] == "data_product" else f"bdm:{camel_case(node['kind'])}"
        statements = [
            f"{node_uri(node_id)} a {rdf_type}",
            f"    rdfs:label {turtle_string(node['label'])}",
            f"    dct:type {turtle_string(node['kind'])}",
            f"    dct:description {turtle_string(node['desc'])}",
        ]
        if node.get("domain"):
            statements.append(f"    bdm:domain {turtle_string(node['domain'])}")
        if node.get("owner"):
            statements.append(f"    dct:publisher {turtle_string(node['owner'])}")
        if node.get("path"):
            statements.append(f"    dcat:distribution {node_uri(node_id + '_distribution')}")
        for rule in node.get("quality", []):
            statements.append(f"    bdm:qualityRule {turtle_string(rule)}")
        for source in incoming_lineage.get(node_id, []):
            statements.append(f"    prov:wasDerivedFrom {node_uri(source)}")

        lines.append(" ;\n".join(statements) + " .")
        lines.append("")

        if node.get("path"):
            lines.extend(
                [
                    f"{node_uri(node_id + '_distribution')} a dcat:Distribution ;",
                    f"    rdfs:label {turtle_string(node['label'] + ' physical distribution')} ;",
                    f"    dcat:accessURL {turtle_string(node['path'])} ;",
                    f"    dct:format {turtle_string(format_for_path(node['path']))} .",
                    "",
                ]
            )

    for source, target, label in EDGES:
        if label == "derived from":
            lines.append(f"{node_uri(target)} prov:wasDerivedFrom {node_uri(source)} .")
        elif label == "joined into":
            lines.append(f"{node_uri(source)} bdm:joinedInto {node_uri(target)} .")
            lines.append(f"{node_uri(target)} prov:wasDerivedFrom {node_uri(source)} .")
        else:
            lines.append(f"{node_uri(source)} {relationship_predicate(label)} {node_uri(target)} .")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def center_x(node: dict) -> float:
    return node["x"] + NW / 2


def center_y(node: dict) -> float:
    return node["y"] + NH / 2


def wrap_label(label: str, max_chars: int = 22) -> list[str]:
    if len(label) <= max_chars:
        return [label]
    words = label.split()
    lines: list[str] = []
    current = ""
    for word in words:
        candidate = f"{current} {word}".strip()
        if len(candidate) > max_chars and current:
            lines.append(current)
            current = word
        else:
            current = candidate
    if current:
        lines.append(current)
    return lines[:2]


def bezier_path(source: dict, target: dict) -> str:
    x1, y1 = source["x"] + NW, center_y(source)
    x2, y2 = target["x"], center_y(target)
    if abs(y1 - y2) < 8:
        return f"M{x1},{y1} L{x2},{y2}"
    mid_x = (x1 + x2) / 2
    return f"M{x1},{y1} C{mid_x},{y1} {mid_x},{y2} {x2},{y2}"


def edge_color(source: dict, target: dict) -> str:
    if target["kind"] == "consumer":
        return "#7F77DD"
    if target["kind"] == "data_product" or source["kind"] == "data_product":
        return "#639922"
    return "#B4B2A9"


def midpoint_bezier(source: dict, target: dict) -> tuple[float, float]:
    x1, y1 = source["x"] + NW, center_y(source)
    x2, y2 = target["x"], center_y(target)
    mid_x = (x1 + x2) / 2
    bx = 0.125 * x1 + 0.375 * mid_x + 0.375 * mid_x + 0.125 * x2
    by = 0.125 * y1 + 0.375 * y1 + 0.375 * y2 + 0.125 * y2
    return bx, by - 6


def should_show_edge_label(source_id: str, target_id: str, label: str) -> bool:
    hidden_edges = {
        ("curated_song_catalog", "streamlit_dashboard"),
        ("song_trend_intelligence", "streamlit_dashboard"),
        ("feedback_events", "streamlit_dashboard"),
        ("feedback_summary", "streamlit_dashboard"),
        ("recommendation_outcomes", "streamlit_dashboard"),
        ("song_embedding_snapshots", "song_recommender_embeddings"),
        ("song_recommender_embeddings", "real_time_recommender"),
        ("real_time_recommender", "recommendation_events"),
    }
    return (source_id, target_id) not in hidden_edges


def edge_label_offset(source_id: str, target_id: str) -> tuple[float, float]:
    offsets = {
        ("trusted_lastfm_tracks", "curated_song_catalog"): (0, -18),
        ("trusted_musicbrainz_isrc", "curated_song_catalog"): (-8, -8),
        ("trusted_reccobeats_audio", "curated_song_catalog"): (-8, 16),
        ("trusted_trends", "song_trend_intelligence"): (-8, -12),
        ("curated_song_catalog", "song_recommender_features"): (14, -10),
        ("song_trend_intelligence", "song_recommender_features"): (14, 14),
        ("song_recommender_features", "song_embedding_snapshots"): (2, -14),
        ("trusted_feedback", "feedback_events"): (0, -12),
        ("trusted_feedback", "feedback_summary"): (-14, 18),
        ("trusted_feedback", "recommendation_outcomes"): (-28, 18),
        ("recommendation_events", "recommendation_outcomes"): (8, -14),
    }
    return offsets.get((source_id, target_id), (0, 0))


def positioned_nodes() -> list[dict]:
    positioned = []
    for node in NODES:
        x, y = POSITIONS[node["id"]]
        positioned.append({**node, "x": x, "y": y})
    return positioned


def write_svg(output_path: Path) -> None:
    nodes = positioned_nodes()
    by_id = {node["id"]: node for node in nodes}
    parts: list[str] = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{VW}" height="{VH}" viewBox="0 0 {VW} {VH}">',
        """
<defs>
  <marker id="arr" viewBox="0 0 10 10" refX="8" refY="5"
          markerWidth="5" markerHeight="5" orient="auto-start-reverse">
    <path d="M2 1L8 5L2 9" fill="none" stroke="context-stroke"
          stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
  </marker>
</defs>""",
        f'<rect width="{VW}" height="{VH}" fill="#ffffff"/>',
        f'<text x="{VW // 2}" y="28" text-anchor="middle" '
        'font-family="Helvetica Neue, Arial, sans-serif" '
        'font-size="15" font-weight="600" fill="#2c2c2a">'
        'Exploitation Zone - Data Product Lineage</text>',
    ]

    for source_id, target_id, label in EDGES:
        source, target = by_id[source_id], by_id[target_id]
        color = edge_color(source, target)
        parts.append(
            f'<path d="{bezier_path(source, target)}" fill="none" stroke="{color}" '
            'stroke-width="1.2" marker-end="url(#arr)"/>'
        )
        if should_show_edge_label(source_id, target_id, label):
            label_x, label_y = midpoint_bezier(source, target)
            offset_x, offset_y = edge_label_offset(source_id, target_id)
            parts.append(
                f'<text x="{label_x + offset_x:.1f}" y="{label_y + offset_y:.1f}" text-anchor="middle" '
                'font-family="Helvetica Neue, Arial, sans-serif" '
                f'font-size="8.7" fill="#888780">{esc(label)}</text>'
            )

    for node in nodes:
        style = KINDS[node["kind"]]
        parts.append(
            f'<rect x="{node["x"]}" y="{node["y"]}" width="{NW}" height="{NH}" rx="{NR}" '
            f'fill="{style["fill"]}" stroke="{style["stroke"]}" stroke-width="0.8"/>'
        )
        label_lines = wrap_label(node["label"])
        if len(label_lines) == 1:
            parts.append(
                f'<text x="{center_x(node)}" y="{node["y"] + NH / 2 - 7}" text-anchor="middle" '
                'font-family="Helvetica Neue, Arial, sans-serif" '
                f'font-size="11" font-weight="600" fill="{style["text"]}" '
                f'dominant-baseline="central">{esc(label_lines[0])}</text>'
            )
        else:
            for idx, line in enumerate(label_lines):
                parts.append(
                    f'<text x="{center_x(node)}" y="{node["y"] + 13 + idx * 12}" text-anchor="middle" '
                    'font-family="Helvetica Neue, Arial, sans-serif" '
                    f'font-size="11" font-weight="600" fill="{style["text"]}" '
                    f'dominant-baseline="central">{esc(line)}</text>'
                )
        parts.append(
            f'<text x="{center_x(node)}" y="{node["y"] + NH - 7}" text-anchor="middle" '
            'font-family="Helvetica Neue, Arial, sans-serif" '
            f'font-size="9" fill="{style["stroke"]}">{esc(node["kind"].replace("_", " "))}</text>'
        )

    legend_x, legend_y = VW - 214, VH - 82
    parts.append(
        f'<rect x="{legend_x - 10}" y="{legend_y - 16}" width="205" height="64" rx="6" '
        'fill="#fafafa" stroke="#d3d1c7" stroke-width="0.5"/>'
    )
    legend = [
        ("Source", KINDS["source"]),
        ("Data product", KINDS["data_product"]),
        ("Supporting asset", KINDS["supporting_asset"]),
        ("Consumer", KINDS["consumer"]),
    ]
    for idx, (label, style) in enumerate(legend):
        row_x = legend_x + (idx % 2) * 100
        row_y = legend_y + (idx // 2) * 24
        parts.append(
            f'<rect x="{row_x}" y="{row_y - 9}" width="10" height="10" rx="2" '
            f'fill="{style["fill"]}" stroke="{style["stroke"]}" stroke-width="0.7"/>'
        )
        parts.append(
            f'<text x="{row_x + 15}" y="{row_y}" '
            'font-family="Helvetica Neue, Arial, sans-serif" '
            f'font-size="9.4" fill="#5f5e5a">{esc(label)}</text>'
        )

    parts.append("</svg>")
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(parts) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate the BDM governance catalog TTL and SVG graph.")
    parser.add_argument("--ttl", default="BDM_P2/metadata/data_product_catalog.ttl", help="Output Turtle path.")
    parser.add_argument("--svg", default="BDM_P2/Images/data_product_catalog_graph.svg", help="Output SVG path.")
    args = parser.parse_args()

    write_ttl(Path(args.ttl))
    write_svg(Path(args.svg))

    print(f"Wrote Turtle catalog: {args.ttl}")
    print(f"Wrote SVG graph: {args.svg}")


if __name__ == "__main__":
    main()
