FROM apache/airflow:3.1.7

RUN pip install --no-cache-dir \
        "deltalake" \
        "polars" \
        "pyarrow" \
        "duckdb" \
        "pandas" \
        "boto3" \
        "minio" \
        "kafka-python==2.3.0" \
        "Pillow" \
        "fastapi" \
        "uvicorn[standard]" \
        "requests"